# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Element.create(name:"" , symbol:"" , atomic_number: , state:"" , group: , atomic_mass: )

# Element.create(name:"hydrogen" , symbol:"H" , atomic_number: 1, state:"gas" , group: 1, atomic_mass: 1)
# Element.create(name:"helium" , symbol:"He" , atomic_number: 2, state:"gas" , group: 18, atomic_mass: 4)
# Element.create(name:"lithium" , symbol:"Li" , atomic_number: 3, state:"solid" , group: 1, atomic_mass: 7)
# Element.create(name:"beryllium" , symbol:"Be" , atomic_number: 4, state:"solid" , group: 2, atomic_mass: 9)
# Element.create(name:"boron" , symbol:"B" , atomic_number: 5, state:"solid" , group: 13, atomic_mass: 11)
# Element.create(name:"carbon" , symbol:"C" , atomic_number: 6, state:"solid" , group: 14, atomic_mass: 12)
# Element.create(name: "nitrogen" , symbol: "N", atomic_number: 7, state: "gas", group: 15, atomic_mass: 14)
# Element.create(name: "oxygen", symbol: "O", atomic_number: 8, state: "gas", group: 16, atomic_mass: 16)
# Element.create(name: "fluorine", symbol: "F", atomic_number: 9, state: "gas", group: 17, atomic_mass: 19)
# Element.create(name: "neon", symbol: "Ne", atomic_number: 10, state: "gas", group: 18, atomic_mass: 20)
# Element.create(name: "sodium", symbol: "Na", atomic_number: 11, state: "solid", group: 1, atomic_mass: 23)
# Element.create(name: "magnesium", symbol: "Mg", atomic_number: 12, state: "solid", group: 2, atomic_mass: 24)
# Element.create(name: "aluminum", symbol: "Al", atomic_number: 13, state: "solid", group: 13, atomic_mass: 27)
# Element.create(name: "silicon", symbol: "Si", atomic_number: 14, state: "solid", group: 14, atomic_mass: 28)
# Element.create(name: "phosphorus", symbol: "P", atomic_number: 15, state: "solid", group: 15, atomic_mass: 31)
# Element.create(name: "sulfur", symbol: "S", atomic_number: 16, state: "solid", group: 16, atomic_mass: 32)
# Element.create(name: "chlorine", symbol: "Cl", atomic_number: 17, state: "gas", group: 17, atomic_mass: 35)
# Element.create(name: "argon", symbol: "Ar", atomic_number: 18, state: "gas", group: 18, atomic_mass: 40)
# Element.create(name: "potassium", symbol: "K", atomic_number: 19, state: "solid", group: 1, atomic_mass: 39)
# Element.create(name: "calcium", symbol: "Ca", atomic_number: 20, state: "solid", group: 2, atomic_mass: 40)
# Element.create(name: "scandium", symbol: "Sc", atomic_number: 21, state: "solid", group: 3, atomic_mass: 45)
# Element.create(name: "titanium", symbol: "Ti", atomic_number: 22, state: "solid", group: 4, atomic_mass: 48)
# Element.create(name: "vandium", symbol: "V", atomic_number: 23, state: "solid", group: 5, atomic_mass: 51)
# Element.create(name: "chromium", symbol: "Cr", atomic_number: 24, state: "solid", group: 6, atomic_mass: 52)
# Element.create(name: "manganese", symbol: "Mn", atomic_number: 25, state: "solid", group: 7, atomic_mass: 55)
# Element.create(name: "iron", symbol: "Fe", atomic_number: 26, state: "solid", group: 8, atomic_mass: 56)
# Element.create(name: "cobalt", symbol: "Co", atomic_number: 27, state: "solid", group: 9, atomic_mass: 59)
# Element.create(name: "nickel", symbol: "Ni", atomic_number: 28, state: "solid", group: 10, atomic_mass: 59)
# Element.create(name: "copper", symbol: "Cu", atomic_number: 29, state: "solid", group: 11, atomic_mass: 64)
# Element.create(name: "zinc", symbol: "Zn", atomic_number: 30, state: "solid", group: 12, atomic_mass: 65)
# Element.create(name: "gallium", symbol: "Ga", atomic_number: 31, state: "solid", group: 13, atomic_mass: 70)
# Element.create(name: "germanium", symbol: "Ge", atomic_number: 32, state: "solid", group: 14, atomic_mass: 73)
# Element.create(name: "arsenic", symbol: "As", atomic_number: 33, state: "solid", group: 15, atomic_mass: 75)
# Element.create(name: "selenium", symbol: "Se", atomic_number: 34, state: "solid", group: 16, atomic_mass: 79)
# Element.create(name: "bromine", symbol: "Br", atomic_number: 35, state: "liquid", group: 17, atomic_mass: 80)
# Element.create(name: "krypton", symbol: "Kr", atomic_number: 36, state: "gas", group: 18, atomic_mass: 84)